### ISSUE TITLE
The em dash in the README displays weirdly

### ISSUE THREAD

**Issue by kdkasad** [MatthewStanciu/purduehackers-jobs#4]
The em dash looks a little weird in a terminal. It's possible that it's just my configuration, but I think it would show up like this on most terminals:
<img width="691" alt="image" src="https://github.com/user-attachments/assets/9a698ba1-6f55-4378-99ce-9510e8dde241">
Maybe we should use 3 hyphens instead?

**Comment by MatthewStanciu** [comment]
Woah weird, what terminal and OS are you using? it displays fine for me on macOS Warp, terminal.app, and iTerm:

<img width="246" alt="Screenshot 2024-08-27 at 10 43 16 PM" src="https://github.com/user-attachments/assets/87c58102-ce70-488c-95f4-f5d30ab0be5c">
<img width="150" alt="Screenshot 2024-08-27 at 10 43 35 PM" src="https://github.com/user-attachments/assets/a1a8fcde-309a-484d-8677-c4ba838182c1">
<img width="168" alt="Screenshot 2024-08-27 at 10 44 14 PM" src="https://github.com/user-attachments/assets/d2fc4c5a-2819-484c-9823-f606cb4f2f0c">

**Comment by kdkasad** [comment]
Oh interesting. I'm using iTerm2. I guess it's just my font...
